### ISSUE TITLE
Feature suggestion: i18n

### ISSUE THREAD

**Issue by kav2k** [knyar/theoldreader-chrome#16]
It's obvious that this extension could benefit from i18n, since we now have an options page.
Also helps with translating extension description.

Guidelines for implementation:
http://developer.chrome.com/extensions/i18n.html

**Comment by MikkCZ** [comment]
I don't think this will need any big changes. Taking this.

**Comment by kav2k** [comment]
Note: besides implementation costs there is ongoing support cost of keeping translations (if any) up to date and make sure submitted translations are not malicious (yes, that can happen).

**Comment by MikkCZ** [comment]
I see. Thankfully chrome.i18n supports fallbacks, so in case the translation is not up to date, in the worst case the user will see English again.

**Comment by kav2k** [comment]
I really don't think there's enough need for this, considering that TOR itself does not have locales other than English.

**Comment by MikkCZ** [comment]
Tor maybe not, but Chrome/Chromium and Firefox do have plenty.

**Comment by MikkCZ** [comment]
And as this add-on provides 3rd party service (The Old Reader) integration, I would expect it to support similar languages portfolio, what the service does. By the way, how is the web ui localization quality and correctness ensured?

**Comment by MikkCZ** [comment]
Hopefully I haven't missed anything [here](https://github.com/MikkCZ/theoldreader-chrome/tree/i18n). But frankly Chrome does not support `.` in the string IDs, so I will need to change all the string IDs. :/

**Comment by MikkCZ** [comment]
Oh, by TOR you meant The Old Reader, not Tor browser. Well, The Old Reader does support other locales. https://github.com/theoldreader/i18n

**Comment by kav2k** [comment]
Oops, indeed it does.
