### ISSUE TITLE
Open in background opens links twice

### ISSUE THREAD

**Issue by aaronsutton** [knyar/theoldreader-chrome#40]
The issue I'm experiencing is that when I press "b" on an article to open it in the background, the link is opened twice, in two separate tabs. This issue occurs on two different machines both running Windows 8.1 and Chrome Version 43.0.2357.73 beta-m (64-bit). Oddly, disabling and re-enabling the extension fixes the issue temporarily.

**Comment by kav2k** [comment]
How "temporarily" is temporarily?
Meanwhile, I'll look into it.

**Comment by aaronsutton** [comment]
I'm not exactly sure. I just disabled and re-enabled and I'll let you know
when it starts to happen again.

--
Aaron

On Thu, May 21, 2015 at 11:01 AM, Alexander Kashev <notifications@github.com

**Comment by kav2k** [comment]
There are 3 possibilities.

1) TOR itself sending the event twice. Dubious - otherwise it would show up regardless of the browser version and we'd hear complaints.
2) Content script sending the message twice. Possible if content script is injected twice - there are no sanity checks against it, but it should not happen.
3) Background script calling the tab-opening code twice. This could happen if the message listener is added twice, however there is no way this can happen.

In principle, I could add the sanity check to the content script, but frankly I'm more inclined to believe in a bug in Chrome Beta channel. If the situation reappears, please contact me - if you could do some diagnostics, it will help.

**Comment by aaronsutton** [comment]
Thanks for the very quick response. I'll write back when the issue occurs
again and we can try to figure out what's going on.

Thanks again.

--
Aaron

On Thu, May 21, 2015 at 12:08 PM, Alexander Kashev <notifications@github.com

**Comment by aaronsutton** [comment]
Hi, so the issue has started again. I'm not sure what's changed. The version is the same (43.0.2357.73 beta-m (64-bit)). I've restarted my computer twice (Surface Pro 3) for various Windows 8.1 updates. You'll have to walk me through debugging steps as I'm not a big coder. That's not to say I don't code, but I don't do any serious development work, I mainly do it for calculations.

**Comment by kav2k** [comment]
The debug steps I need involve inspecting two components of the extension with Developer Tools.

Step 1, I need you to open Dev Tools Console on the affected TOR page with Ctrl+Shift+J, find the `<top frame>` context selector, and tell me how many entries for the Notifier are there.

**Comment by kav2k** [comment]
Step 2, I need you to select the Notifier context and execute the following in the console:

    chrome.runtime.sendMessage({openInBackground: true, url: "http://example.com/"});

and tell me if that opens it twice.

**Comment by aaronsutton** [comment]
Hi, thanks for walking me through this. There is only one notifier context
in the context selector menu and running the above code opens only one page.

--
Aaron

**Comment by kav2k** [comment]
Okay, then I need one more step to confirm. In the same console, execute this:

    var event = new CustomEvent("tor:openPostInBackground", {detail: "http://example.com/"});
    window.dispatchEvent(event);

**Comment by aaronsutton** [comment]
That opens the page twice.

--
Aaron

**Comment by kav2k** [comment]
Okay, that confirms where the fault lies.

I still don't know how it gets triggered, but I can easily add a sanity check for that.

Thanks for the diagnosis, I will push an update when I can.

**Comment by aaronsutton** [comment]
Thanks so much!

**Comment by kav2k** [comment]
Update pushed out. Expect it to go live in a few hours.
