### ISSUE TITLE
Explicit license

### ISSUE THREAD

**Issue by kav2k** [knyar/theoldreader-chrome#41]
This project lacks an explicit license.

As the current maintainer, I would like to clarify what flavor of open-source this is. I personally prefer MIT license.

We need input from all code contributors: pinging @knyar, @nelchael, @krasnoukhov, @ConcurrentHashMap, @SqREL. Would you object to licensing the code you contributed under MIT license? If yes, what would you prefer instead?

**Comment by krasnoukhov** [comment]
No objection on my side! Thanks for your work @kav2k

**Comment by nelchael** [comment]
No objections, MIT is OK.

**Comment by knyar** [comment]
MIT is my license of choice as well, so no objections.
Thanks for taking care of this, @kav2k.

**Comment by ConcurrentHashMap** [comment]
For sure, go MIT.

**Comment by kav2k** [comment]
@SqREL contacted out of band (via Telegram) and agreed to MIT.

That covers all code contributors; I will draft a license notice.
