### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by MikkCZ** [knyar/theoldreader-chrome#43]
Current nighty versions of Firefox 57 have already disabled legacy (XUL) add-ons and once the version is released in the stable channel (November 2017), the current extension for Firefox will stop working, as only WebExtensions will be supported. The best way to address it would be to port this to Firefox, hopefully only repacking will be needed. I will take a look on it in the coming days.

**Comment by kav2k** [comment]
This shouldn't be too hard. I'm happy to provide porting help, but I need help with testing.

**Comment by kav2k** [comment]
This also runs into the question "who will be the uploader for AMO".
For CWS, both me and @knyar have access to update the "official" extension release.
Does AMO support developer groups? Should I be the one uploading it?

**Comment by MikkCZ** [comment]
I have few minutes now, so I have [temporary loaded](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) the extensions (as-is) and the major stuff work in the current Firefox 56.0b2. The icon is displayed and after logging in, the number of unread items too. So what does not work from what I have noticed?

1. Show changelog link opens Get Add-ons panel.
2. Rate in Google Chrome Web Store is not appropriate for Firefox. Not sure if it's possible to do some browser detection there to display a different link (or at least hide this one) for Firefox.
3. Show right-click context menu - the add-on entry is in the context menu, but does not open for me (what should be there?). Maybe this is related to the temporary loading, maybe not.
4. As Firefox does not support Chrome Sync (it has Firefox Sync instead), the Sync options preference is also extra here. Not sure what is does anyway.
5. Click button to save changes text displays under the save button. This is a minor issue an can be probably replaced by saving the preferences on the fly. I have seen it working in https://github.com/erkserkserks/h264ify.

**Comment by MikkCZ** [comment]
Hi @kav2k.

Yes, AMO allows to add more people to an add-on with different permissions (edit add-on page, upload new versions etc.). There also should be some API for uploading new versions automatically, but at this moment I do not know, what's the status of it and how it works.

The best option would be to somehow get in touch with the current [Firefox add-on](https://addons.mozilla.org/en-US/firefox/addon/the-old-reader-notifier/) author. That way the WebExt version could be uploaded with the same ID and all users will get updated. If a new add-on is created, they will need to find it manually. In the latter case, I would suggest the same person uploading the add-on to the Chrome store should take care of AMO too.

Anyway I will be happy with testing. But looking at the issues, I need to compare with the behaviour in Chrome, to be sure I do not miss anything in Firefox.

**Comment by jfiorato** [comment]
@kav2k @MikkCZ I've been trying over the last few months to get a hold of the current FF add-on author, as TOR team has been receiving bug reports for the unread count not updating. He has been unresponsive.

**Comment by kav2k** [comment]
1. This is an `<a href="#">` element with a click listener. Perhaps that does not play well with Firefox's options pages - and in general is not good practice, if I remember correctly. This needs to be redone.
2. Yes, such browser detection can be done in this case. The simplest is to just look for `browser`, which is present in Firefox but not Chrome. Perhaps a more semantically correct approach can be taken, or, better yet, different builds for FF and Chrome.
3. The menu has two forms; page context should have two sub-items, "Subscribe to page" and "Bookmark page", while text selection should have "Bookmark selection". See `source/js/menu.js`. I assume (without checking docs) that FF does not support `onclick` handler form; the whole code should be refactored for `chrome.contextMenu.onClicked` listener, which is better practice anyway. If there are no sub-items, then incompatibility runs deeper and I'll need to look into it.
4. I think this can simply be reworded (and possibly shown conditionally as in 2). This option allows to detach local options from cloud ones (if unchecked), which can be useful if you want separate options on separate machines.
5. I'll need to look at it.

**Comment by MikkCZ** [comment]
@jfiorato Actually I have e-mailed him some time ago too, about porting his add-on to WebExt. Did not realized there is already a version for Chrome. But as I am not the only one not able to reach him, the repacked version need to be submitted as a "new add-on" instead.

@kav2k I will try to pack for Firefox later and install it into the browser a proper way. All features, that the XUL add-on from Tomek has, work fine. So from this point of view, there would be no regression for the users if it's uploaded without any changes.

**Comment by kav2k** [comment]
Some organizational decisions to be made. Please voice your opinions on the subject.

How should we accommodate for a Firefox version?
1. Fork, separate repo.
2. Same repo, different branches.
3. Same repo, same branch, multiple sources (+build system).

How to deal with FF issues?
1. Keep them to this issue with a checklist.
2. Split it into smaller issues.

@MikkCZ, how involved do you want to be in this? Can I assign some tasks to you?

**Comment by kav2k** [comment]
Personally, I think we should keep it to one repo, one branch for release code and split this issue into many (maybe with a Project board).

**Comment by MikkCZ** [comment]
I think the we should keep the code for all browsers as close as possible, that's also the meaning behind WebExtensions. I have made some updates to the add-on to fix the names in options and enable sync in Firefox. See https://github.com/MikkCZ/theoldreader-chrome/tree/firefox

**Comment by kav2k** [comment]
Remaining issues after merging #44:
- #45 
- #46 
- #47 
- #48 
- #50 
- #51

After that we can submit, and then fix #49

**Comment by kav2k** [comment]
While technically still under review, the add-on is up at https://addons.mozilla.org/en-US/firefox/addon/the-old-reader-notifier-webext/

Thanks @MikkCZ for the motivation and initial work on this.

@jfiorato I shall inform you when it's published so you can update the listing on your end.

**Comment by kav2k** [comment]
Good news everyone, the extension is up.

@jfiorato If you could add the extension on your end at https://theoldreader.com/pages/apps marked as "Firefox 54+ WebExtension", it would be great. Keeping the old one might me worth it since some people stick with the older version where WebExtensions are not yet supported (due to reliance on older extensions).

**Comment by jfiorato** [comment]
Just updated our apps page. Will also send an update via Facebook and Twitter. Let me know if you want any changes in attribution on our apps page. Thanks so much for helping with this guys.

https://theoldreader.com/pages/apps

**Comment by knyar** [comment]
+1 to changing attribution. I have not touched this code in several years, it's fair to call out @kav2k as the main author.

**Comment by MikkCZ** [comment]
@jfiorato Thank you for mentioning me contribution on https://theoldreader.com/pages/apps. Just a note to the link, can you change it to https://addons.mozilla.org/firefox/addon/the-old-reader-notifier-webext/ (without the en-US, which forces the English version of the page)?

**Comment by jfiorato** [comment]
@MikkCZ All set. Sorry about that.
