### ISSUE TITLE
Fix Bookmark context menu items for FF

### ISSUE THREAD

**Issue by kav2k** [knyar/theoldreader-chrome#47]
Stage 1:
- [x] Don't add those context menu items in FF.
 
Stage 2:
- [ ] Rework the handlers to deal with FF restrictions (no `javascript:` URLs in `chrome.tabs`).

**Comment by kav2k** [comment]
@MikkCZ If you're itching to help this needs more immediate attention.

TL;DR of the problem: we need to open a new tab and POST from it (AJAX won't do since we must show the reply to continue the process).

Previously that was done with a `javascript:` URL; now we need to implement something more like [this solution](https://stackoverflow.com/questions/7387217/chrome-extension-development-post-to-new-tab/23687543#23687543).

**Comment by MikkCZ** [comment]
I have only free The Old Reader plan, so I cannot try this.

**Comment by jfiorato** [comment]
If you can send me your account email/username to jfiorato@theoldreader.com, I'll upgrade you.

**Comment by MikkCZ** [comment]
I will look at this today.

**Comment by kav2k** [comment]
@MikkCZ I'm doing some more linting right now: be prepared to update your base branch.
