### ISSUE TITLE
Autosave options

### ISSUE THREAD

**Issue by MikkCZ** [knyar/theoldreader-chrome#53]
Autosaving options is actually not so hard as it might look. See [`Options.js`](https://github.com/MikkCZ/rotate-and-zoom-image/blob/4a7c4d233287a738307982280d7dfb6f7b7e6491/src/js/Options.js) and [`options-ui.js`](https://github.com/MikkCZ/rotate-and-zoom-image/blob/4a7c4d233287a738307982280d7dfb6f7b7e6491/src/js/options-ui.js), that do the work for me.

**Comment by kav2k** [comment]
I need to check if I already implemented `sync` rate limiting..

But yes, in principle this should not be too hard. Though there may be corner cases.

**Comment by kav2k** [comment]
Yes, there is a retry mechanism if sync storage hits rate limits.

**Comment by kav2k** [comment]
My main worry with using `change` event: what happens if the user changes a textbox input value, then closes the page without losing focus? Is the system robust enough to process that? Needs testing.

**Comment by MikkCZ** [comment]
I have made a quick test  and at least in Firefox it works.

**Comment by MikkCZ** [comment]
A bit improved version of the code mentioned in the report comment is in my https://github.com/MikkCZ/pontoon-tools, where it will probably get more frequent updates. At this moment it is used with inputs of type text, number and checkbox, and with selects (options added both programatically or hardcoded in the template). Feel free to accomodate it to your needs, if you get to this ticket before me. :)

**Comment by kav2k** [comment]
*carefully eyes partial-copyleft MPL license from a safe distance*

**Comment by MikkCZ** [comment]
As it's my code, I can make it available under any license needed here. ;)

**Comment by MikkCZ** [comment]
I want to move the Options.js and the scripts around to a standalone repository se it's available for anyone to use. I will let here know after it's done. https://github.com/MikkCZ/pontoon-tools/issues/68

**Comment by MikkCZ** [comment]
Closing (as won't fix) given the add-on development seems stopped anyway.
