### ISSUE TITLE
Fix Makefile. Again.

### ISSUE THREAD

**Issue by kav2k** [knyar/theoldreader-chrome#54]
Unsurprisingly, my attempts at making the Makefile better failed; this needs to be looked at again.

Requirements:

* Must have `all`, `firefox`, `chrome` and `clean` targets.
* Must default to `all`.
* `firefox` and `chrome` must build both uncompressed and compressed versions.
* Must properly rebuild in case of empty `build/` - _currently failing_
* Must properly detect and rebuild if anything is changed in `source/`

**Comment by MikkCZ** [comment]
Maybe you can make use of [web-ext](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) and [Chrome directly](https://developer.chrome.com/extensions/packaging#packaging).

**Comment by kav2k** [comment]
@MikkCZ Neither of those things is really needed: since the extension is distributed via CWS/AMO, no signing of CRX/XPI is required locally. Both stores expect _just_ a ZIP.

It's just a question of small tweaks to targets. I have it done already on another project, haven't pushed changes here yet.

**Comment by MikkCZ** [comment]
I wonder, if the presence of "application" actualy breaks the add-on for Chrome. What happens, if you package for Chrome with the firefox manifest.json? Maybe we never actually needed the two manifest approach.

**Comment by kav2k** [comment]
Last time I checked, it did. Also, for more complex cases (not this addon) there may be other differences between manifests (e.g. a permission only recognized on one).

**Comment by kav2k** [comment]
Seems to be working fine after tweaks.
