### ISSUE TITLE
The state with new rss items and no new is hard to catch by eye

### ISSUE THREAD

**Issue by MikkCZ** [knyar/theoldreader-chrome#60]
I suggest to change the color of the icon to gray when there are no unread items, and change to red when there are some.

**Comment by kav2k** [comment]
Sooo the existence of a badge is hard to catch?

Sorry, I don't think it's appropriate. The color changes to gray when there's no data to rely on (connection error, logged out) - it already has established semantics.

**Comment by kav2k** [comment]
One could maybe make the active badge color configurable. That way, it's not red-on-red. How's that for a visibility solution?

**Comment by MikkCZ** [comment]
I did not realize the gray icon is already used in any situation. But making the badge color configurable will definitely help (at least my eyes) to spot there is something new to read.

**Comment by MikkCZ** [comment]
Closing (as won't fix) given the add-on development seems stopped anyway.
