### ISSUE TITLE
Not supported in Firefox 57.0

### ISSUE THREAD

**Issue by EsquimauxQC** [knyar/theoldreader-chrome#61]
The plugin appears in the following list since I upgraded to Firefox 57.0:

These extensions do not meet current Firefox standards so they have been deactivated.

**Comment by kav2k** [comment]
I think there is some confusion.

The old ["The Old Reader Notifier"](https://addons.mozilla.org/en-US/firefox/addon/the-old-reader-notifier/) (by Tomek Wasiak) add-on is indeed no longer supported - and unfortunately we were not able to contact the author to take it over to provide a smooth upgrade path or take it down. This is _not_ the repository for that version.

Instead, a new ["The Old Reader Notifier"](https://addons.mozilla.org/en-US/firefox/addon/the-old-reader-notifier-webext/) (by Xan, i.e. me) was published and is fully compatible with Quantum / FF57+.

**Comment by EsquimauxQC** [comment]
Thanks... that was it!
